config/routes.rb
Rails.application.routes.draw do
    
  resources :forms do 
    collection do 
      post :import 
    end
  end

  # resources :survey do 
  #   collection { post :import_xml }
  # end

  resources :farmers do 
    resources :forms do 
      resources :questions do 
        resources :answers
      end
      resources :scores
    end
  end

  root to: "admin/dashboard#index"

  match '/submission' => 'farmers#receive_answers', as: 'submission', via: :post
  match '/formList' => 'survey_xmls#getforms', as: 'formList', via: :get
  

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  devise_for :views

  match '*path', to: 'pages#error_404', via: :all
end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :form
	has_many :answers, dependent: :destroy
end

app/controllers/questions_controller.rb
class QuestionsController < InheritedResources::Base

  private

    def question_params
      params.require(:question).permit(:name, :content)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %><br>
    <%= f.text_field :question %>
  </div>
  <div class="field">
    <%= f.label :question_name %><br>
    <%= f.text_field :question_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Questions</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Question name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.question %></td>
        <td><%= question.question_name %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @question.question %>
</p>

<p>
  <strong>Question name:</strong>
  <%= @question.question_name %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>