config/routes.rb
Rails.application.routes.draw do
    
  resources :forms do 
    collection do 
      post :import 
    end
  end

  # resources :survey do 
  #   collection { post :import_xml }
  # end

  resources :farmers do 
    resources :forms do 
      resources :questions do 
        resources :answers
      end
      resources :scores
    end
  end

  root to: "admin/dashboard#index"

  match '/submission' => 'farmers#receive_answers', as: 'submission', via: :post
  match '/formList' => 'survey_xmls#getforms', as: 'formList', via: :get
  

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  devise_for :views

  match '*path', to: 'pages#error_404', via: :all
end

app/models/score.rb
class Score < ActiveRecord::Base
  belongs_to :form
  belongs_to :farmer

  validates_presence_of :total, :maximum_total

  PASSED = "passed"
  FAILED = "failed"

  def self.locate_score(farmer_id, form_id)
    Score.where("farmer_id = :farmer_id and form_id = :form_id",  {farmer_id: farmer_id, form_id: form_id})
  end

  def state
    self.total/self.maximum_total * 100  < 75 ? FAILED : PASSED
  end
end

app/controllers/scores_controller.rb
class ScoresController < InheritedResources::Base

  private

    def score_params
      params.require(:score).permit(:form_id, :major_must, :minor_must, :total)
    end
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/scores/_form.html.erb
<%= form_for(@score) do |f| %>
  <% if @score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
      <% @score.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :form_id %><br>
    <%= f.text_field :form_id %>
  </div>
  <div class="field">
    <%= f.label :major_must %><br>
    <%= f.text_field :major_must %>
  </div>
  <div class="field">
    <%= f.label :minor_must %><br>
    <%= f.text_field :minor_must %>
  </div>
  <div class="field">
    <%= f.label :total %><br>
    <%= f.text_field :total %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scores/edit.html.erb
<h1>Editing Score</h1>

<%= render 'form' %>

<%= link_to 'Show', @score %> |
<%= link_to 'Back', scores_path %>

app/views/scores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Scores</h1>

<table>
  <thead>
    <tr>
      <th>Form</th>
      <th>Major must</th>
      <th>Minor must</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scores.each do |score| %>
      <tr>
        <td><%= score.form %></td>
        <td><%= score.major_must %></td>
        <td><%= score.minor_must %></td>
        <td><%= score.total %></td>
        <td><%= link_to 'Show', score %></td>
        <td><%= link_to 'Edit', edit_score_path(score) %></td>
        <td><%= link_to 'Destroy', score, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Score', new_score_path %>

app/views/scores/new.html.erb
<h1>New Score</h1>

<%= render 'form' %>

<%= link_to 'Back', scores_path %>

app/views/scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Form:</strong>
  <%= @score.form %>
</p>

<p>
  <strong>Major must:</strong>
  <%= @score.major_must %>
</p>

<p>
  <strong>Minor must:</strong>
  <%= @score.minor_must %>
</p>

<p>
  <strong>Total:</strong>
  <%= @score.total %>
</p>

<%= link_to 'Edit', edit_score_path(@score) %> |
<%= link_to 'Back', scores_path %>