config/routes.rb
Rails.application.routes.draw do
    
  resources :forms do 
    collection do 
      post :import 
    end
  end

  # resources :survey do 
  #   collection { post :import_xml }
  # end

  resources :farmers do 
    resources :forms do 
      resources :questions do 
        resources :answers
      end
      resources :scores
    end
  end

  root to: "admin/dashboard#index"

  match '/submission' => 'farmers#receive_answers', as: 'submission', via: :post
  match '/formList' => 'survey_xmls#getforms', as: 'formList', via: :get
  

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  devise_for :views

  match '*path', to: 'pages#error_404', via: :all
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :farmer
  belongs_to :form
end

app/controllers/answers_controller.rb
class AnswersController < InheritedResources::Base

  private

    def answer_params
      params.require(:answer).permit(:question_id, :answer, :description)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%= form_for(@answer) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question_id %><br>
    <%= f.text_field :question_id %>
  </div>
  <div class="field">
    <%= f.label :answer %><br>
    <%= f.text_field :answer %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Answers</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Answer</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.question %></td>
        <td><%= answer.answer %></td>
        <td><%= answer.description %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @answer.question %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @answer.answer %>
</p>

<p>
  <strong>Description:</strong>
  <%= @answer.description %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>