config/routes.rb
Rails.application.routes.draw do
    
  resources :forms do 
    collection do 
      post :import 
    end
  end

  # resources :survey do 
  #   collection { post :import_xml }
  # end

  resources :farmers do 
    resources :forms do 
      resources :questions do 
        resources :answers
      end
      resources :scores
    end
  end

  root to: "admin/dashboard#index"

  match '/submission' => 'farmers#receive_answers', as: 'submission', via: :post
  match '/formList' => 'survey_xmls#getforms', as: 'formList', via: :get
  

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  devise_for :views

  match '*path', to: 'pages#error_404', via: :all
end

app/controllers/forms_controller.rb
class FormsController < InheritedResources::Base

  def getforms
    @forms = Form.all
    render xml: @forms, content_type: "text/xml"
  end

  def import
    Form.import(params[:file])
    redirect_to root_url, notice: "Survey Questions Imported"
  end

  private

    def form_params
      params.require(:form).permit(:farmer_id, :name, :odk_key)
    end
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/views/forms/_form.html.erb
<%= form_for(@form) do |f| %>
  <% if @form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@form.errors.count, "error") %> prohibited this form from being saved:</h2>

      <ul>
      <% @form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :farmer_id %><br>
    <%= f.text_field :farmer_id %>
  </div>
  <div class="field">
    <%= f.label :form_name %><br>
    <%= f.text_field :form_name %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/forms/edit.html.erb
<h1>Editing Form</h1>

<%= render 'form' %>

<%= link_to 'Show', @form %> |
<%= link_to 'Back', forms_path %>

app/views/forms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Forms</h1>

<table>
  <thead>
    <tr>
      <th>Farmer</th>
      <th>Form name</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @forms.each do |form| %>
      <tr>
        <td><%= form.name %></td>
        <td><%= link_to 'Show', form %></td>
        <td><%= link_to 'Edit', edit_form_path(form) %></td>
        <td><%= link_to 'Destroy', form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Form', new_form_path %>
<h2> Import Questions Spreadsheet </h2>
<%= form_tag import_forms_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

app/views/forms/new.html.erb
<h1>New Form</h1>

<%= render 'form' %>

<%= link_to 'Back', forms_path %>

app/views/forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Farmer:</strong>
  <%= @form.farmer %>
</p>

<p>
  <strong>Form name:</strong>
  <%= @form.form_name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @form.date %>
</p>

<%= link_to 'Edit', edit_form_path(@form) %> |
<%= link_to 'Back', forms_path %>